### ISSUE TITLE
在Catserver运行会导致服务器无法启动

### ISSUE THREAD

**Issue by 849025143** [Heliecp/RoadChina#2]
最新版 CatServer 1.12.2
最新版 RoadChina
java.lang.NoSuchMethodError: heliecp.roadchina.Tab.WhiteLine.func_78021_a()I
	at heliecp.roadchina.Tab.YellowLine.<init>(YellowLine.java:12)
	at heliecp.roadchina.Tab.YellowLine.<clinit>(YellowLine.java:9)
	at heliecp.roadchina.Block.BlockRegistry.<clinit>(BlockRegistry.java:16)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_255_BlockRegistry_onRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:852)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:169)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Epochwood** [comment]
收到，正在排查问题，感谢反馈

**Comment by Epochwood** [comment]
已发现问题解决办法，但目前由于1.12.2版本需重置（暑假），所以修复的版本将会在暑假发布，多谢支持。

**Comment by Epochwood** [comment]
相关问题现已解决，请耐心等待新版本发布，感谢您的支持与反馈！
